# Generated by Django 4.1.2 on 2023-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('salary', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblemployee',
            },
        ),
    ]
